### ISSUE TITLE
Header v2 "gap" bug on mobile

### ISSUE THREAD

**Issue by daylesalmon** [wmcadigital/wmn-design-system#730]
**Describe the bug**
There is a gap that appears when you open the search/I want to section on a mobile device.
This only seems to happen on smaller web pages.

**Expected behavior**
No gap at the top of the header

**Screenshots**
![image](https://user-images.githubusercontent.com/13015201/114365492-694a8300-9b72-11eb-954a-bddf705d8923.png)

**Additional context**
It is an easy fix of adding `top:0;` to the CSS block below:

```scss 
@media screen and (max-width: 767px)
.wmnds-header--search-open {
    position: fixed;
    width: 100%;
}
```
